apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      affinity:
            nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                          nodeSelectorTerms:
                          - matchExpressions:
                            - key: node-role.kubernetes.io/master
                              operator: Exists
      volumes:
      - name: data
        emptyDir: {}
      - name: redis-config
        configMap:
         name: redis-config
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        - name: data
          mountPath: /opt
        - name: redis-config
          mountPath: /etc/config
        resources: 
           requests:
             cpu: "0.2"
status: {}
