apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k8s-challenge-3"
