apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb3
  name: bb3
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - "ls;sleep 3600"
    image: busybox
    name: bb1
    resources: {}
  - command:
    - /bin/sh
    - -c
    - "echo Hello World;sleep 3600"
    image: busybox
    name: bb2
    resources: {}
  - command:
    - /bin/sh
    - -c
    - "echo this is 3rd container; sleep 3600"
    image: busybox
    name: bb3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
