apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb4
  name: bb4
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: log-volume
      mountPath: /usr/share/nginx/html
  - command:
    - /bin/sh
    - -c
    - while true;do echo 'Hi, I am from Main container' >> /var/log/index.html; sleep 5; done
    image: busybox
    name: bb4
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
