apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: c2
  name: c2
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo HW and time_freq is $TIME_FREQ && sleep 600
    image: busybox
    name: c2
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
