apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: c3
  name: c3
spec:
  volumes:
  - name: config-volume
    configMap:
      name: time-config
  containers:
  - command:
    - /bin/sh
    - -c
    - echo HW && sleep 600
    image: busybox
    name: c3
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
