apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-cmvolume
  name: nginx-cmvolume
spec:
  volumes:
    - name: cm-volume
      configMap:
        name: cmvolume
  containers:
  - image: nginx
    name: nginx-cmvolume
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/lala
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
