apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob1-td
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1-td
            image: kodekloud/throw-dice 
          restartPolicy: OnFailure
