apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
 containers:
 - name: test
   image: nginx
   volumeMounts:
   - name: sada
     mountPath: /tmp
 nodeSelector:
    run: master
 volumes:
 - name: sada
   hostPath: 
     path: /data
