apiVersion: v1
kind: Pod
metadata:
 name: secret-pod
spec:
 containers:
 - name: secret-pod
   image: busybox
   command:
   - /bin/sh
   - "-c"
   - "echo the secret is $DB_PASSWORD && sleep 3600"
   env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
