apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: config-pod
  name: config-pod
spec:
  containers:
  - command:
    - /bin/sh
    - "-c"
    - "echo Hello World! and $TIME_FREQ && sleep 3600"
    image: busybox
    name: config-pod
    env:
    - name: TIME_FREQ
      valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
