apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 600
    image: busybox
    name: bb
    volumeMounts:
    - name: mysql-mount
      mountPath: /etc/
  volumes:
  - name: mysql-mount
    persistentVolumeClaim:
      claimName: mysql-pv-claim
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
