apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: log-claim
  containers:
  - image: nginx:alpine
    name: logger
    volumeMounts:
    - name: log-volume 
      mountPath: /var/www/nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
