apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx-anotherone
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
        name: anotherone 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
