apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxd
  name: nginxd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxd
    spec:
      containers:
      - image: nginxd
        ports:
        - containerPort: 80
        name: nginxd
        resources: {}
status: {}
