apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: aa
  name: aa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aa
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aa
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
