apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080
  type: NodePort
  selector:
    app: redis
status:
  loadBalancer: {}
