apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: s1
  name: s1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo HW && sleep 600
    image: busybox
    name: s1
    envFrom:
    - secretRef:
        name: db-password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
