apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: s2
  name: s2
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo HW and password is $DB_PASSWORD && sleep 600
    image: busybox
    name: s2
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-password
          key: password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
