apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: s3
  name: s3
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: db-password
  containers:
  - command:
    - /bin/sh
    - -c
    - echo HW && sleep 600
    image: busybox
    name: s3
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
