apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
spec:
  volumes:
  - name: life-volume
    emptyDir: {}
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do date; sleep ; done > /opt/time/time-check.log
    image: busybox
    name: time-check
    envFrom:
    - configMapRef:
       name: time-config
    volumeMounts:
    - name: life-volume
      mountPath: /opt/time
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
