apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: no-downtime
  name: pod-calc
spec:
  containers:
  - image: nginx
    name: pod-calc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
