apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: no-downtime
  name: nginx
  namespace: one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: no-downtime
  template:
    metadata:
     labels:
       app: no-downtime
    spec:
      containers:
      - image: nginx
        name: pod-calc
