apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-25T00:50:13Z"
  name: nginx
  namespace: one
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
