apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-25T18:49:55Z"
  labels:
    run: nginx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-05-25T18:49:55Z"
  name: np-svc
  namespace: default
  resourceVersion: "830874"
  selfLink: /api/v1/namespaces/default/services/np-svc
  uid: 138cc30e-0e97-45e2-b4e2-38428176eae0
spec:
  clusterIP: 10.103.20.221
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
