apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash
  name: bash
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: secret1
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 600
    image: bash
    name: bash
    envFrom:
    - configMapRef:
        name: liquid-cm
    volumeMounts:
    - name: secret-volume
      mountPath: /tmp/secret1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
