apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: mypvc
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: bb
    volumeMounts:
    - name: my-pvc
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
